#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const THEMES_DIR = path.join(__dirname, '..', 'themes');
const CSS_OUTPUT = path.join(__dirname, '..', 'styles', 'generated-themes.css');
const TS_OUTPUT = path.join(__dirname, '..', 'lib', 'generated', 'themes.ts');

function discoverThemes() {
  if (!fs.existsSync(THEMES_DIR)) {
    console.log('No themes directory found, skipping theme generation');
    return [];
  }

  const entries = fs.readdirSync(THEMES_DIR, { withFileTypes: true });
  const themes = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const themeName = entry.name;
    const themeJsonPath = path.join(THEMES_DIR, themeName, 'theme.json');

    if (!fs.existsSync(themeJsonPath)) {
      console.warn(`Warning: Skipping theme '${themeName}' - missing theme.json`);
      continue;
    }

    try {
      const themeData = JSON.parse(fs.readFileSync(themeJsonPath, 'utf-8'));

      if (!themeData.colors || !themeData.colors.light || !themeData.colors.dark) {
        console.warn(`Warning: Skipping theme '${themeName}' - missing required colors.light or colors.dark`);
        continue;
      }

      themes.push({
        name: themeName,
        data: themeData
      });
    } catch (error) {
      console.warn(`Warning: Failed to parse theme.json for '${themeName}': ${error.message}`);
    }
  }

  return themes;
}

const SPECIAL_KEYS = new Set(['color-scheme', 'background', 'foreground']);

function toCSSDeclaration(key, value) {
  if (key === 'color-scheme') return `color-scheme: ${value};`;
  if (SPECIAL_KEYS.has(key)) return `--${key}: ${value};`;
  return `--saffron-${key}: ${value};`;
}

function generateCSS(themes) {
  let css = '/* Auto-generated by scripts/generate-themes.js — do not edit manually */\n\n';

  for (const theme of themes) {
    const { name, data } = theme;

    // Generate light mode
    css += `:root[data-theme="${name}"][data-color-mode="light"] {\n`;
    for (const [key, value] of Object.entries(data.colors.light)) {
      css += `  ${toCSSDeclaration(key, value)}\n`;
    }
    css += '}\n\n';

    // Generate dark mode
    css += `:root[data-theme="${name}"][data-color-mode="dark"] {\n`;
    for (const [key, value] of Object.entries(data.colors.dark)) {
      css += `  ${toCSSDeclaration(key, value)}\n`;
    }
    css += '}\n\n';
  }

  return css;
}

function generateTypeScript(themes) {
  const themeNames = themes.map(t => `"${t.name}"`).join(', ');
  
  let ts = '// Auto-generated by scripts/generate-themes.js — do not edit manually\n';
  ts += `export const DISCOVERED_THEMES = [${themeNames}] as const;\n`;
  ts += 'export type DiscoveredThemeName = typeof DISCOVERED_THEMES[number];\n\n';
  
  ts += 'export interface ThemeMeta {\n';
  ts += '  displayName: string;\n';
  ts += '  logo: string; // relative path from themes/{name}/\n';
  ts += '}\n\n';
  
  ts += 'export const THEME_META: Record<DiscoveredThemeName, ThemeMeta> = {\n';
  
  for (let i = 0; i < themes.length; i++) {
    const { name, data } = themes[i];
    const comma = i < themes.length - 1 ? ',' : '';
    ts += `  ${name}: { displayName: "${data.displayName}", logo: "${data.logo}" }${comma}\n`;
  }
  
  ts += '};\n';
  
  return ts;
}

function main() {
  console.log('Discovering themes...');
  const themes = discoverThemes();

  if (themes.length === 0) {
    console.log('No valid themes found');
    
    // Write minimal/empty outputs
    const emptyCSS = '/* Auto-generated by scripts/generate-themes.js — do not edit manually */\n/* No themes found */\n';
    const emptyTS = '// Auto-generated by scripts/generate-themes.js — do not edit manually\nexport const DISCOVERED_THEMES = [] as const;\nexport type DiscoveredThemeName = typeof DISCOVERED_THEMES[number];\nexport interface ThemeMeta { displayName: string; logo: string; }\nexport const THEME_META: Record<DiscoveredThemeName, ThemeMeta> = {};\n';
    
    fs.mkdirSync(path.dirname(CSS_OUTPUT), { recursive: true });
    fs.mkdirSync(path.dirname(TS_OUTPUT), { recursive: true });
    fs.writeFileSync(CSS_OUTPUT, emptyCSS);
    fs.writeFileSync(TS_OUTPUT, emptyTS);
    
    console.log('Generated empty output files');
    return;
  }

  console.log(`Found ${themes.length} theme(s): ${themes.map(t => t.name).join(', ')}`);

  // Generate CSS
  console.log('Generating CSS...');
  const css = generateCSS(themes);
  fs.mkdirSync(path.dirname(CSS_OUTPUT), { recursive: true });
  fs.writeFileSync(CSS_OUTPUT, css);
  console.log(`✓ Generated ${CSS_OUTPUT}`);

  // Generate TypeScript
  console.log('Generating TypeScript...');
  const ts = generateTypeScript(themes);
  fs.mkdirSync(path.dirname(TS_OUTPUT), { recursive: true });
  fs.writeFileSync(TS_OUTPUT, ts);
  console.log(`✓ Generated ${TS_OUTPUT}`);

  console.log('Theme generation complete!');
}

main();
